apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: wanderlust-ingress
spec:
  rules:
  - http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: frontend-service   # ⚠️ IMPORTANT
            port:
              number: 80             # ⚠️ IMPORTANT
